<h2 class="mainBox">Наши продукты</h2>

<!--set params-->
    <?php $url=URL.'/product/index/page/';?>
<?php $limit        = $controller->getSessParam('limit'); ?>
<?php $orderType    = $controller->getSessParam('ordertype'); ?>
<?php $orderBy      = $controller->getSessParam('orderByProduct'); ?>
<?php $currentPage  = $view->getParam('currentPage'); ?>
<?php $products     = $view->getParam('products'); ?>

<?php if(!empty($products)) :?>

<!--include limit for items-->
<?php include SITE_PATH.DS.'View'.DS.'limit.phtml';?>
<div>

<!-- menu for sort-->
<div id="productTitle">
    <p>Cортировать по:
    
    <a href='<?= $url.$currentPage;?>/orderby/name'>Имени<?php if($orderBy == 'name') :?>&darr;<?php endif; ?></a>
    <a href='<?= $url.$currentPage;?>/orderby/price'>Цене<?php if($orderBy == 'price') :?>&darr;<?php endif; ?></a>
    <a href='<?= $url.$currentPage;?>/orderby/total'>Количеству<?php if($orderBy == 'total') :?>&darr;<?php endif; ?></a>
    </p>
    <p>
    <a href='<?= $url.$currentPage;?>/ordertype/asc'>по возрастанию<?php if($orderType == 'asc') :?>&darr;<?php endif; ?></a>
    <a href='<?= $url.$currentPage;?>/ordertype/desc'>по убыванию<?php if($orderType == 'desc') :?>&darr;<?php endif; ?></a> 
    </p>
</div>

<!--print items-->
    <?php foreach($products as $product) : ?>
    <?php
        $src    = URL.'/img/img.png';
        $imgUrl =('/img/Products/'.$product->img);           
        if($product->img != NULL && is_readable(SITE_PATH.$imgUrl)){$src = URL.$imgUrl;}        
    ?>
    <div id="product" class="mainBox"> 
        <div><img alt="<?='img-'.$product->img;?>" src="<?=$src?>"></div>
        <div><?= $product->name;?></div>
        <div><?= $product->price;?></div>
        <div><?= $product->description;?></div>
        <div><?= $product->total;?></div>
    </div>
        <?php endforeach; ?>
</div>

<!--include pagination-->
    <?php 
    $countPages = ceil($view->getParam('countProducts') / $limit);
    if($countPages>1){include SITE_PATH.DS.'View'.DS.'paginator.phtml';}
    ?>

<?php  elseif($view->getParam('error')) : ?>
    <div style="color:red;"><h1><?php echo $view->getParam('error')?></h1></div>
<?php endif; ?>