<?php include 'menu.phtml';?>
<?php $url=URL.'/admin/customer/page/';?>
<?php $limit        = $controller->getSessParam('limit'); ?>
<?php $orderType    = $controller->getSessParam('ordertype'); ?>
<?php $orderBy      = $controller->getSessParam('orderByCustomer'); ?>
<?php $currentPage  = $view->getParam('currentPage'); ?>
<?php $customers     = $view->getParam('customers'); ?>

<h2 class="mainBox">ADmin клиенты</h2>
<h3><a href="<?=URL.'/admin/Info'?>">Добавить нового</a></h3>
<?php include SITE_PATH.DS.'View'.DS.'limit.phtml';?>

<?php if(!empty($customers)) :?>
    <table align="center">
        <tr>
            <th></th>
            <?php if($orderType == 'asc') : ?>
                <th><a href='<?php echo $url.$currentPage;?>/orderby/login/ordertype/desc'>login<?php if($orderBy == 'login') :?>&darr;<?php endif; ?></a></th>
                <th><a href='<?php echo $url.$currentPage;?>/orderby/email/ordertype/desc'>email<?php if($orderBy == 'email') :?>&darr;<?php endif; ?></a></th>
                <th><a href='<?php echo $url.$currentPage;?>/orderby/photo/ordertype/desc'>photo<?php if($orderBy == 'photo') :?>&darr;<?php endif; ?></a></th>
                <th><a href='<?php echo $url.$currentPage;?>/orderby/skills/ordertype/desc'>skills<?php if($orderBy == 'skills') :?>&darr;<?php endif; ?></a></th>
                <th><a href='<?php echo $url.$currentPage;?>/orderby/role_id/ordertype/desc'>role_id<?php if($orderBy == 'role_id') :?>&darr;<?php endif; ?></a></th>
            <?php else : ?>
                <th><a href='<?php echo $url.$currentPage;?>/orderby/login/ordertype/asc'>login<?php if($orderBy == 'login') :?>&uarr;<?php endif; ?></a></th>
                <th><a href='<?php echo $url.$currentPage;?>/orderby/email/ordertype/asc'>email<?php if($orderBy == 'email') :?>&uarr;<?php endif; ?></a></th>
                <th><a href='<?php echo $url.$currentPage;?>/orderby/photo/ordertype/asc'>photo<?php if($orderBy == 'photo') :?>&uarr;<?php endif; ?></a></th>
                <th><a href='<?php echo $url.$currentPage;?>/orderby/skills/ordertype/asc'>skills<?php if($orderBy == 'skills') :?>&uarr;<?php endif; ?></a></th>
                <th><a href='<?php echo $url.$currentPage;?>/orderby/role_id/ordertype/asc'>role_id<?php if($orderBy == 'role_id') :?>&uarr;<?php endif; ?></a></th>
            <?php endif; ?>  
               <th></th>  
        </tr>        
    <?php foreach($customers as $customer) : ?>
    <tr>   
        <td><a href="#">change</a></td>
        <td class="mainBox"><?php echo $customer->login;?></td>
        <td class="mainBox"><?php echo $customer->email;?></td>
        <td class="mainBox"><?php echo $customer->photo;?></td>
        <td class="mainBox"><?php echo $customer->skills;?></td>
        <td class="mainBox"><?php echo $customer->role_id;?></td>
        <td><a href="#">delete</a></td>
    </tr>
        <?php endforeach; ?>   
</table>

    <?php 
    $countPages = ceil($view->getParam('countCustomers') / $limit);
    if($countPages>1){include SITE_PATH.DS.'View'.DS.'paginator.phtml';}
    ?>
<?php endif; ?>