<form>
    <div>    
    <label for="name">Product name</label>
    <input type="text" name="name" id="name">
    </div>
    <div>
     <label for="price">Price</label>
     <input type="number" name="price" id="price">  
    </div>
    <div>
     <label for="total">Total</label>
     <input type="number" name="total" id="total">  
    </div>
    <div>
     <label for="description">description</label>
     <textarea name="description" id="description"></textarea>
    </div>
    <div>
     <label for="img">img</label>
     <input type="file" name="img" id="img">  
    </div>        
</form>