<?php
$errorType = $view->getParam('error');
$errorMessage = '';
    if(!empty($errorType)) {
        switch($errorType) {
            case System_Exception::ALREADY_EXIST:
                $errorMessage = 'Product already exists!';
                break;
            case System_Exception::FILE_ERROR:
                $errorMessage = 'Can not upload file';
                break;
            case System_Exception::FILE_EXIST:
                $errorMessage = 'File whis this name already exists!';
                break;
        }
    }
$product     = $view->getParam('product');
$currentPage  = $view->getParam('currentPage');
$url=URL.'/Admin/product';
$src    = URL.'/img/img.png';
if(!empty($product))
    {
    $url.='/id/'.$product->id;
    $name=$product->name;
    $description = $product->description;
    $price= $product->price;
    $total= $product->total;
    $imgUrl =('/img/Products/'.$product->img);        
    if($product->img != NULL && is_readable(SITE_PATH.$imgUrl)){$src = URL.$imgUrl;}    
    }
        
    
    
        
?>
<div class="mainBox" id="body">
<div class="error"><?=$errorMessage?></div>
<form action="<?=$url.'/page/'.$currentPage.'/set/1'?>" method="POST" enctype="multipart/form-data">
    <div>
     <label for="img"><img alt="<?='img-'.$product->img;?>" src="<?=$src?>"></label>
     <input type="file" name="img" id="img">  
    </div>
    <div id="forLabel">    
    <label for="name">Name</label>
    <label for="price">Price</label>
    <label for="total">Total</label>
    </div>
    <div id="forInput">
    <input type="text" name="name" id="name" value="<?=$name?>"placeholder="new name">
    <input type="number" name="price" id="price" value="<?=$price?>" placeholder="new price">  
    <input type="number" name="total" id="total" value="<?=$total?>"placeholder="new total">
    </div>    
    <div>
     <label for="description">description</label><br/>
     <textarea name="description" id="description"><?=$description?></textarea>
    </div>    
    <div>
        <input type="submit" value="Ok">
        <input type="reset" value="Reset">
    </div>
</form>
<form action="<?=URL.'/Admin/product'.'/page/'.$currentPage?>">
    <input type="submit" value="Cansel">
</form>
</div>