<?php include 'menu.phtml';?>
<h2>ADmin продукты</h2>
<?php $url=URL.'/admin/product/page/';?>
<?php $currentPage  = $view->getParam('currentPage'); ?>
<?php $limit        = $view->getParam('limit'); ?>
<?php $orderType    = $view->getParam('orderType'); ?>
<?php $orderBy      = $view->getParam('orderBy'); ?>
<?php $products     = $view->getParam('products'); ?>
<a href="<?=URL.'/admin/productInfo'?>">add new product</a></br>
<a class="gallery2" title="Простая HTML" href="<?php echo URL.'/admin/customer/page/'?>">Клик</a>
<?php if(!empty($products)) :?>
    <table align="center">
        <tr>
            <th></th>
            <?php if($orderType == 'asc') : ?>
                <th><a href='<?php echo $url.$currentPage;?>/orderby/img/ordertype/desc'>Img<?php if($orderBy == 'img') :?>&darr;<?php endif; ?></a></th>
                <th><a href='<?php echo $url.$currentPage;?>/orderby/name/ordertype/desc'>Name<?php if($orderBy == 'name') :?>&darr;<?php endif; ?></a></th>
                <th><a href='<?php echo $url.$currentPage;?>/orderby/name/ordertype/desc'>description<?php if($orderBy == 'description') :?>&darr;<?php endif; ?></a></th>
                <th><a href='<?php echo $url.$currentPage;?>/orderby/price/ordertype/desc'>Price<?php if($orderBy == 'price') :?>&darr;<?php endif; ?></a></th>
                <th><a href='<?php echo $url.$currentPage;?>/orderby/total/ordertype/desc'>Total<?php if($orderBy == 'total') :?>&darr;<?php endif; ?></a></th>
            <?php else : ?>
                <th><a href='<?php echo $url.$currentPage;?>/orderby/img/ordertype/asc'>Img<?php if($orderBy == 'img') :?>&uarr;<?php endif; ?></a></th>
                <th><a href='<?php echo $url.$currentPage;?>/orderby/name/ordertype/asc'>Name<?php if($orderBy == 'name') :?>&uarr;<?php endif; ?></a></th>
                <th><a href='<?php echo $url.$currentPage;?>/orderby/name/ordertype/asc'>description<?php if($orderBy == 'description') :?>&uarr;<?php endif; ?></a></th>
                <th><a href='<?php echo $url.$currentPage;?>/orderby/price/ordertype/asc'>Price<?php if($orderBy == 'price') :?>&uarr;<?php endif; ?></a></th>
                <th><a href='<?php echo $url.$currentPage;?>/orderby/total/ordertype/asc'>Total<?php if($orderBy == 'total') :?>&uarr;<?php endif; ?></a></th>
            <?php endif; ?>  
               <th></th>  
        </tr>        
    <?php foreach($products as $product) : ?>
    <?php /** @var Model_Product $product*/ ?>   
    <tr>   
        <td><a href="#">chenge</a></td>
        <td><?php echo $product->img;?></td>
        <td><?php echo $product->name;?></td>
        <td><?php echo $product->description;?></td>
        <td><?php echo $product->price;?></td>
        <td><?php echo $product->total;?></td>
        <td><a href="<?=$url.$currentPage.'/remove/true/id/'.$product->id?>">delete</a></td>
    </tr>
        <?php endforeach; ?>   
</table>

    <?php $countPages = ceil($view->getParam('countProducts') / $limit);
    if($countPages>1){
                include SITE_PATH.DS.'View'.DS.'paginator.phtml';}
    ?>

<?php endif; ?>