<?php 
    $userId = $controller->getUserId();
          
    $userRoleId = 0;
    if($userId) {
        $userModel      = Model_User::getById($userId);
        $userEmail      = $userModel->email;
        $userRoleId     = $userModel->role_id; 
    }

    $errorType = $controller->getParamByKey('error');
    $errorMessage = '';
    if(!empty($errorType)) {
        switch($errorType) {
            case System_Exception::ALREADY_EXIST:
                $errorMessage = 'Such account already exists!';
                break;
            case System_Exception::VALIDATE_ERROR:
                $errorMessage = 'Invalid enetered data!';
                break;
            case System_Exception::ERROR_CREATE_USER:
                $errorMessage = 'Can\'t create new user! Try again!';
                break;
            case System_Exception::INVALID_LOGIN:
                $errorMessage = 'Invalid user or password!';
                break;    
        }
    } 
?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title><?php echo $_SERVER['SERVER_NAME'];?></title>
        <link href="<?= URL; ?>/css/layout.css" rel="stylesheet" type="text/css"/>
        <link href="<?= URL.'/css/'.$viewFolder.'/'.$actionName.'.css'; ?>" rel="stylesheet" type="text/css"/>
        <script type="text/javascript" src="<?= URL;?>/js/jquery.js"></script>
        <script type="text/javascript" src="<?= URL;?>/js/authorize.js"></script>
        
        <!-- Add mousewheel plugin (this is optional) -->
        <script type="text/javascript" src="<?= URL?>/fancybox/lib/jquery.mousewheel-3.0.6.pack.js"></script>

        <!-- Add fancyBox -->
        <link rel="stylesheet" href="<?= URL?>/fancybox/source/jquery.fancybox.css?v=2.1.5" type="text/css" media="screen" />
        <script type="text/javascript" src="<?= URL?>/fancybox/source/jquery.fancybox.pack.js?v=2.1.5"></script>

        <script type="text/javascript" src="<?= URL.'/js/'.$viewFolder.'/'.$actionName.'.js'?>"></script>
    </head>    
    <body>    
        <div id="error" class="error"><?=$errorMessage?></div>
        <div <?= !empty($userId) ?'':'style="display: none;"';?> class="mainBox" id="userEnter">
        <div id="userEmail">'Вы зашли как:<a href="<?=URL?>/user/profile/id/<?=$userId?>"><?php echo !empty($userEmail) ? $userEmail : ''; ?></a></div>
        <div id="userId"><a id="logout" href="#"><?php echo !empty($userId) ? 'Exit' : ''?></a></div>    
        </div>
        <div <?=!empty($userEmail)? 'style="display: none;"':''?> id="loginFormDiv">
            <form name="autorize" id="loginForm" method="POST" autocomplete="off">
                <input placeholder="Login" type="text" name="email" maxlength="20" /><br />
                <input placeholder="Password" type="password" name="password" maxlength="30" /><br />
                <input id="save_checkbox" type="checkbox" name="save" value="1" /><label for="save_checkbox">Save</label><br />
                <input type="submit" name="login" value="Enter" />
                <input type="submit" name="register" value="Register" />
            </form>
        </div>            
        <div id="menu" class="mainBox">
                <a href="<?php echo URL;?>/">Главная </a> 
                <a href="<?php echo URL;?>/product/index">Продукты </a>
                <a href="<?php echo URL;?>/company/portfolio">Портфолио </a>
                <a href="<?php echo URL;?>/company/about">О компании </a>
                <a href="<?php echo URL;?>/company/contact">Контакты </a>                
                <a id="admin_href" href="<?php echo URL;?>/admin/index" <?php if($userRoleId != Model_User::ROLE_ADMIN_ID) { echo 'style="display: none;"'; } ?>>Админка </a>
            </div>
        <?php 
        $scriptFile = 'js' . '/' . $viewFolder . '/' . $actionName. '.js';
        if(file_exists($scriptFile)): ?>
            <script src="<?php  echo URL.'/' . $scriptFile; ?>"></script>
        <?php endif; ?>
        <br />
        <hr />
    <div id="forContent">
    <?php
        if(file_exists($viewFileName)) {
            include $viewFileName;
        }
    ?>
    </div>
    </body>
    
</html>