<div id="limit" class="mainBox">
    <label>Записей на странице &#9660;</label>       
        <div>
        <a href='<?= $url.'1';?>/limit/3'>3<?php if($limit == '3') :?>&darr;<?php endif; ?></a>
        <a href='<?= $url.'1';?>/limit/5'>5<?php if($limit == '5') :?>&darr;<?php endif; ?></a>
        <a href='<?= $url.'1';?>/limit/10'>10<?php if($limit == '10') :?>&darr;<?php endif; ?></a>
        <a href='<?= $url.'1';?>/limit/15'>15<?php if($limit == '15') :?>&darr;<?php endif; ?></a>
        <a href='<?= $url.'1';?>/limit/20'>20<?php if($limit == '20') :?>&darr;<?php endif; ?></a>
        </div>        
</div>