<?php 
// Входные параметры
  $countShowPages = 5;
  $halfShowPages=floor($countShowPages / 2);
    $left = $currentPage - 1;
    $right = $countPages - $currentPage;
    if ($left < $halfShowPages) $start = 1;
    else $start = $currentPage - $halfShowPages;
    $end = $start + $countShowPages - 1;
    if ($end > $countPages) {
      $start -= ($end - $countPages);
      $end = $countPages;
      if ($start < 1) $start = 1;
    }
?>
  <!-- вывод Pagination -->
  <div id="pagination">
    <?php echo $currentPage==1?'Предыдущая':'<a href="'.$url.($currentPage - 1).'" title="Предыдущая страница">Предыдущая</a>';?>
      <?php if ($left > $halfShowPages): ?>      
      <a href="<?=$url.'1'?>" title="Первая страница">1...</a>
    <?php endif; ?>
    <?php for ($i = $start; $i <= $end; $i++): ?>
      <?php echo $i == $currentPage ? '<span>'.$i.'</span>':'<a href="'.$url.$i.'">'.$i.'</a>';?>
    <?php endfor; ?>
    <?php if ($right >$halfShowPages): ?>      
      <a href="<?=$url.$countPages?>" title="Последняя страница">...<?=$countPages?></a>      
    <?php endif; ?>
     <?php echo $currentPage==$countPages?'Следующая':'<a href="'.$url.($currentPage + 1).'" title="Следующая страница">Следующая</a>';?>
  </div>